_BASE_: ./config/BASE.yaml

data:
  vost:

    path: ../datasets/VOST/VOST
    path_test: ../datasets/DAVIS/DAVIS/VOST_test
    path_unique_mask_ids_train_set: ./datasets/vost/dict_mask_unique_ids_train.pkl
    fps_jittering_file: null
    fps_jittering_range: [1, 2, 3, 4]

    use_test_transform: False
    use_ignore_threshold: False
    use_rand_reverse: False
    use_aot_version: False


# Hyperparams
lr: 1e-4                                            # modded for 16 GPUs
lr_backbone: 2e-5                                   # modded for 16 GPUs
# text_encoder_lr: 1e-4

lr_drop: 20

flop_count_mode: False

# Model
model:
  name: 
    tubedetr: tubedetr_vost_multi_scale_memory
    transformer: transformer_vost_multi_scale_memory
    backbone: backbone

  segment_types: ["fg", "left_trun", "right_trun", "bg"]
  use_score_per_frame: True                           # to predict score per frame

  use_single_query_embed: False

  vost:
    max_num_objects: 16
    video_max_len: 20
    use_projection_layer: True
    freeze_backbone_during_query_projection: False
    use_text_encoder: False

    train_seg_head_only: false

    reuse_input_proj_for_image_in_memory: False
    separate_input_proj_for_all: False

    attention_encoder: "space"
    attention_decoder: "cross_attention"
    use_second_last_feature: False

    video_query_concat_at_feature_level: False


    pixel_decoder:
      name: "PixelDecoderUsingTransformerEncodedFeatures"  # (BasePixelDecoder,MSDeformAttnPixelDecoder)
      conv_dim: 256
      mask_dim: 256
      norm: "GN"
      in_features: ["res2", "res3", "res4", "res5"]

      decode_mask_image_too: False

    memory:
      clip_length: 3
      bank_size: 2

      teacher_forcing:
        enable: False

      rel_time_encoding: False
      rel_time_encoding_type: "linear_add" #["linear_mul", "embedding_add", "embedding_mul"]
      abs_time_encoding: False

      use_spatialtemporal_attn: False
      split_ST_branch: True
      use_spatialtemporal_attn_v2: False
      use_bg_matching: False

    parts_exp:
      decoder:
        multiple_queries:
          enable: false
          num_queries_per_frame: 4


joint:
  scale_loss:
    vost: 1.0



# tasks
tasks:
  names: ['vost']
train_strategy: "concat"                            # ['round_robin']



# Train arguments
train_flags:
  print_freq: 100
  
  vost:
    stride: 0
    eval_set_size:
      train: 20
      debug: 10
    sample_query_mask_not_necessarily_from_first_frame: false
    train_mask_head_in_ft_mode: false

    multi_object:
      enable: False
      num_objects: 2
      unified_encoding: False
      iterate_over_all_clips: False

    memory:
      preseve_0th_frame: False

    ann_file: ''

    

# Eval arguments
eval_flags:
  print_freq: 100
  use_full_video_for_eval: True                     # flag for using full videos or not
  plot_pred: False                                  # to plot predictions
  evaluation_jitter: False
  TTA:
    enable: False
    scales: [1.0, 1.1, 0.9, 0.8, 1.2]
    aggregate_memory: True
    # scales: [1.0]

  vost:
    stride: 0
    # window_step_size: 5
    use_fg_score_to_mask_bg:
      enable: False
      lower_thres: 0.3
      # upper_thres: 0.0
    eval_first_window_only: False
    eval_second_window_only: False
    w_reference_slide: True
    use_gt_intermediates: False

    multi_object:
      enable: False

    # visualization
    vis_only_no_cache: False
    vis_only_pred_mask: False
    
    confidence_threshold: 0.5

    split: 'all'  # we support 'all', 'LNG', 'MI', 'SM'
    fps10: False
    ann_file: ''
    interpolate_RTE: '' # [original bs, expanded bs]


# Loss coefficients
loss_coef:
  score_per_frame_loss_coef: 2
  vost:
    mask: 5
    dice: 5
    mask_alpha: 0.25
    reweighting: False
    reweighting_type: "area" # ["cc", "cm", "area"], where cc: connected components, cm: center of mass
    reweighting_tau: 1.0
    reweighting_focal: True
    reweighting_dice: False


flops_exp:
  enable: False
  downsample_factor: 1




misc:
  # MISC - MQ
  mq:
    extract_backbone_features: False        # flag for extracting mq backbone features
    path_extract_backbone_features: data/mq_root/extracted_backbone_features/dummy